site_name: Sistema Multiagentes Anti-DoS
theme:
  name: material

nav:
  - Início: index.md
  - Visão Geral: overview.md
  - Arquitetura dos Agentes: agentes.md
  - Roteamento HTTP: rotas.md
  - Relatórios: relatorios.md
  - Execução: execucao.md
  - Estrutura de Pastas: estrutura.md
